version: '3.4'

networks:
    backend:
    frontend:

services:
  database:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=password@123 
    volumes:
        - db_data:/var/lib/mysql 
    networks:
        - backend
  resultsapi:
    container_name: app-api
    image: ${DOCKER_REGISTRY-}resultsapi
    build:
      context: .
      dockerfile: ResultsApi\ResultsApi\Dockerfile
    depends_on:
        - database
    environment:
        - DB_HOST=database
        - DB_NAME=Results     
        - DB_SA_PASSWORD=password@123
    networks:
        - backend
        - frontend
  ui:
    image: holdens-movies
    build:
      context: .
      dockerfile: HoldenMovies\Dockerfile
    ports:
      - '4200:80'
    networks:
      - frontend


volumes:
  db_data:
    driver: local